name: foodie
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  video_player:
  http: any
  
  path: ^1.6.4
  crypto: ^2.1.3
  loading: ^1.0.2
  share: ^0.6.3
  #permission: ^0.1.5
  fluttertoast: ^3.1.3
  image_picker: ^0.6.1+1
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.1.1
  firebase_storage: ^3.0.6
  firebase_auth: ^0.14.0
  shared_preferences: ^0.5.4+6
  cached_network_image: ^2.0.0
  flutter_facebook_login: ^3.0.0
  google_maps_flutter: ^0.5.21+12
  flutter_datetime_picker: ^1.2.8
  flutter_calendar_carousel: ^1.4.8
  #horizontal_calendar_widget: ^1.0.1
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/6327.png
    - images/logo.png
    - images/isotipo.png
    - images/facebook_icon.png
    - images/google_icon.png
    - images/6328.png
    - images/6329.png
    - images/elipse127.png
    - images/elipse128.png
    - images/pass_icon.png
    - images/flag.png
    - images/certifiedicon.png
    - images/foodicon.png
    - images/img_menu_experiencias.png
    - images/img_menu_listas.png
    - images/img_menu_mis_reservas.png
    - images/img_menu_restaurantes.png
    - images/listsicon.png
    - images/planner_01.png
    - images/user_01.png
    - images/camara_01.png
    - images/foodicon_01.png
    - images/favoritos_01.png
    - images/promocion.png
    - images/group_5.png
    - images/postular_rest.png
    - images/img_resultado.png
    - images/img_resultado2.png
    - images/cup.png
    - images/hat.png
    - images/reservado.png
    - images/plate1.png
    - images/plate2.png
    - images/plate3.png
    - images/banner.png
    - images/man.png
    - images/back_icon_02.png
    - images/detalle_02.png
    - images/boton_compartir.png
    - images/boton_favoritos.png
    - images/boton_planner.png
    - images/mail_safe.png
    - images/icon_intro_planner.png
    - images/boton_compartir.png
    - images/boton_favoritos.png
    - images/boton_planner.png
    - images/boton_compartir_red.png
    - images/boton_favoritos_red.png
    - images/boton_planner_red.png
    - images/icon_list_01.png
    - images/icon_pos_02.png
    - images/icon_list_02.png
    - images/icon_pos_01.png
    - images/eye.png
    - images/icon_gallery.png
    - images/icon_video.png
    - images/rate.png
    - images/comment.png
    - images/rate1.png
    - images/options.png
    - images/regresar.png
    - images/mail_icon.png
    - images/bed_01.png
    - images/plane_01.png
    - images/banner2.png
    - images/check.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand Light
      fonts:
        - asset: fonts/quicksand-light.ttf

    - family: Quicksand Regular
      fonts:
        - asset: fonts/quicksand.ttf

    - family: Quicksand Bold
      fonts:
        - asset: fonts/quicksand-bold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
